INSERT INTO employee (id, first_name, last_name, email, phone_number, date_of_birth, monthly_salary) VALUES (1, "Milan", "Vukicevic", "mvukicevic992@gmail.com", 0637308050, "1992-09-04", 680.0);
INSERT INTO employee (id, first_name, last_name, email, phone_number, date_of_birth, monthly_salary) VALUES (2, "Pera", "Peric", "pera@gmail.com", 0691231231, "1994-03-24", 820.0);
INSERT INTO employee (id, first_name, last_name, email, phone_number, date_of_birth, monthly_salary) VALUES (3, "Ana", "Anic", "ana@gmail.com", 0639879879, "1996-04-14", 710.0);
INSERT INTO employee (id, first_name, last_name, email, phone_number, date_of_birth, monthly_salary) VALUES (4, "Jovan", "Jovanovic", "jovan@gmail.com", 0614564564, "1997-01-09", 1050.0);
INSERT INTO employee (id, first_name, last_name, email, phone_number, date_of_birth, monthly_salary) VALUES (5, "Sima", "Simic", "sima@gmail.com", 0627897897, "1991-12-17", 630.0);
INSERT INTO employee (id, first_name, last_name, email, phone_number, date_of_birth, monthly_salary) VALUES (6, "Dunja", "Dunjic", "dunja@gmail.com", 0643563563, "1998-08-01", 970.0);
INSERT INTO employee (id, first_name, last_name, email, phone_number, date_of_birth, monthly_salary) VALUES (7, "Ivana", "Ivanovic", "ivana@gmail.com", 0600204030, "1995-05-19", 840.0);

INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (1, "Test 1", "Knowledge of the basic concepts of object programming", 1, "2023-03-13", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (2, "Test 2", "Basic knowledge of Eclipse", 2, "2023-03-14", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (3, "Test 3", "Basic knowledge of working with databases (SQL)", 3, "2023-03-15", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (4, "Test 4", "Ability to use Maven tools", 4, "2023-03-16", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (5, "Test 5", "Basics of Spring", 5, "2023-03-17", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (6, "Test 6", "Basics of Spring Boot", 6, "2023-03-17", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (7, "Test 7", "Basics of MVC", 7, "2023-01-17", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (8, "Test 8", "Using GIT", 1, "2023-02-17", false);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (9, "Test 9", "Using external Java libraries", 2, "2023-02-17", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (10, "Test 10", "Using the JUnit library for software testing", 3, "2023-03-09", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (11, "Test 11", "Using the Eclipse java EE environment", 1, "2023-03-06", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (12, "Test 12", "Knowledge of Dependency injection", 2, "2023-03-03", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (13, "Test 13", "Ability to program a basic web application that uses a database", 2, "2023-03-04", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (14, "Test 14", "Sposobnost izrade kompetne veb aplikacije bazirane MVC arhitekturi", 6, "2023-03-05", false);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (15, "Test 15", "Knowledge of the basics of object-relational mapping", 7, "2023-03-10", false);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (16, "Test 16", "Using Spring Data JPA with Hibernate implementation", 2, "2023-01-11", true);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (17, "Test 17", "Knowledge of REST concepts", 4, "2023-02-24", false);
INSERT INTO task (id, title, description, assignee_id, due_date, is_completed) VALUES (18, "Test 18", "Authorization and Authentication", 1, "2023-02-25", true);